package org.careflow.domain;

public enum CareJourneyState {
    NEW,
    TRIAGED,
    CONSULTATION_REQUIRED,
    CONSULTED,
    DIAGNOSTIC_REQUIRED,
    DIAGNOSTIC_IN_PROGRESS,
    DIAGNOSTIC_COMPLETED,
    REFERRAL_REQUIRED,
    REFERRAL_ACCEPTED,
    APPOINTMENT_CONFIRMED,
    TRANSPORT_CONFIRMED,
    PATIENT_ARRIVED,
    TREATMENT_COMPLETED,
    MEDICINE_FULFILLED,
    FOLLOW_UP_ACTIVE,
    CLOSED
}
