"""
CareFlow Freshness, Provenance & Reality-Aware Telemetry Engine
Implements 5-tier data freshness classification, 3-tier data reality labels,
confidence scoring, TTL evaluation, and transparent provenance badges.
"""
from dataclasses import dataclass
from datetime import datetime, timezone, timedelta
from enum import Enum
from typing import Any, Optional


class FreshnessClass(str, Enum):
    CLASS_A_TRANSACTION_REAL_TIME = "TRANSACTION_REAL_TIME"  # Generated during active transaction (Referral, Booking, Consent)
    CLASS_B_NEAR_REAL_TIME = "NEAR_REAL_TIME"               # Frequent polling/webhook (Bed load, Lab queue, Stock)
    CLASS_C_PERIODIC_BATCH = "PERIODIC_BATCH"               # Scheduled batch sync (Daily indicators, HMIS, Program sync)
    CLASS_D_STATIC_REFERENCE = "STATIC_REFERENCE"           # Registry reference (HFR facility registry, HPR doctor list)
    CLASS_U_UNKNOWN_UNVERIFIED = "UNKNOWN_UNVERIFIED"       # Source capability or availability cannot be determined


class DataReality(str, Enum):
    REAL_EXTERNAL = "REAL_EXTERNAL"        # Data received from an authorized live external system
    SANDBOX_EXTERNAL = "SANDBOX_EXTERNAL"  # Data received from an official government sandbox/testbed
    SIMULATED = "SIMULATED"                # Data generated by local contract mock / synthetic double


class TransportStatusSource(str, Enum):
    LIVE_GPS = "LIVE_GPS"              # GPS coordinates updated within <60s (Simulated or Real feed)
    PERIODIC = "PERIODIC"              # Checkpoint updates (e.g. at dispatch, pickup)
    EVENT_ONLY = "EVENT_ONLY"          # State change notices without live position
    UNAVAILABLE = "UNAVAILABLE"        # No transport telemetry feed


class VerificationStatus(str, Enum):
    SOURCE_VERIFIED = "SOURCE_VERIFIED"
    STALE = "STALE"
    UNVERIFIED = "UNVERIFIED"
    EXPIRED = "EXPIRED"
    CAPABILITY_UNKNOWN = "CAPABILITY_UNKNOWN"


# Default TTLs per data type in seconds
DEFAULT_TTLS: dict[str, int] = {
    "specialist_availability": 1800,       # 30 minutes
    "bed_capacity": 900,                   # 15 minutes
    "diagnostic_queue": 1800,              # 30 minutes
    "medicine_stock": 3600,                # 60 minutes
    "ambulance_gps": 60,                   # 1 minute
    "facility_registry": 86400 * 7,        # 7 days (static HFR)
    "consent_token": 86400 * 30,           # 30 days
    "teleconsultation_slot": 600           # 10 minutes
}


@dataclass
class FreshnessMetadata:
    source_system: str
    source_record_id: Optional[str]
    observed_at: datetime
    received_at: datetime
    valid_until: datetime
    freshness_class: FreshnessClass
    data_reality: DataReality
    confidence: float  # 0.0 to 1.0
    verification_status: VerificationStatus
    data_type: str = "generic"
    provenance_hash: Optional[str] = None

    @classmethod
    def create(
        cls,
        source_system: str,
        source_record_id: Optional[str],
        data_type: str,
        freshness_class: FreshnessClass,
        data_reality: DataReality = DataReality.SIMULATED,
        observed_at: Optional[datetime] = None,
        custom_ttl_seconds: Optional[int] = None
    ) -> "FreshnessMetadata":
        now = datetime.now(timezone.utc)
        obs = observed_at or now
        ttl = custom_ttl_seconds or DEFAULT_TTLS.get(data_type, 3600)
        valid_until = obs + timedelta(seconds=ttl)

        if freshness_class == FreshnessClass.CLASS_U_UNKNOWN_UNVERIFIED:
            return cls(
                source_system=source_system,
                source_record_id=source_record_id,
                observed_at=obs,
                received_at=now,
                valid_until=now,
                freshness_class=freshness_class,
                data_reality=data_reality,
                confidence=0.0,
                verification_status=VerificationStatus.CAPABILITY_UNKNOWN,
                data_type=data_type
            )

        # Baseline confidence based on freshness class
        base_confidence = {
            FreshnessClass.CLASS_A_TRANSACTION_REAL_TIME: 1.0,
            FreshnessClass.CLASS_B_NEAR_REAL_TIME: 0.90,
            FreshnessClass.CLASS_C_PERIODIC_BATCH: 0.70,
            FreshnessClass.CLASS_D_STATIC_REFERENCE: 0.85
        }.get(freshness_class, 0.5)

        age_seconds = max(0.0, (now - obs).total_seconds())
        decay_factor = max(0.2, 1.0 - (age_seconds / (ttl * 2.0)))
        confidence = round(base_confidence * decay_factor, 2)

        status = VerificationStatus.SOURCE_VERIFIED if now <= valid_until else VerificationStatus.STALE

        return cls(
            source_system=source_system,
            source_record_id=source_record_id,
            observed_at=obs,
            received_at=now,
            valid_until=valid_until,
            freshness_class=freshness_class,
            data_reality=data_reality,
            confidence=confidence,
            verification_status=status,
            data_type=data_type
        )

    def is_fresh(self) -> bool:
        if self.freshness_class == FreshnessClass.CLASS_U_UNKNOWN_UNVERIFIED:
            return False
        return datetime.now(timezone.utc) <= self.valid_until

    def get_ui_badge(self) -> dict[str, Any]:
        """Returns honest, transparent provenance and reality badge for UI rendering."""
        now = datetime.now(timezone.utc)
        age_minutes = int(max(0, (now - self.observed_at).total_seconds()) // 60)
        
        if age_minutes == 0:
            time_str = "just now"
        elif age_minutes < 60:
            time_str = f"{age_minutes}m ago"
        else:
            time_str = f"{age_minutes // 60}h ago"

        reality_tag = f"[{self.data_reality.value}]"

        if self.freshness_class == FreshnessClass.CLASS_U_UNKNOWN_UNVERIFIED:
            badge_type = "unknown"
            badge_text = f"{reality_tag} Source capability unknown / unverified"
        elif self.is_fresh():
            badge_type = "verified"
            badge_text = f"{reality_tag} Verified {time_str} via {self.source_system}"
        else:
            badge_type = "stale"
            badge_text = f"{reality_tag} Stale ({time_str}) — Availability cannot be confirmed. Action: Call facility"

        return {
            "badge_type": badge_type,
            "badge_text": badge_text,
            "data_reality": self.data_reality.value,
            "confidence_percent": int(self.confidence * 100),
            "source_system": self.source_system,
            "freshness_class": self.freshness_class.value,
            "is_fresh": self.is_fresh()
        }


class FreshnessEngine:
    """Manages multi-source data feeds, TTL monitoring, and stale-data safety degradation."""

    def __init__(self):
        self._registry: dict[str, FreshnessMetadata] = {}

    def register(self, key: str, metadata: FreshnessMetadata) -> None:
        self._registry[key] = metadata

    def get(self, key: str) -> Optional[FreshnessMetadata]:
        return self._registry.get(key)

    def evaluate(self, key: str) -> dict[str, Any]:
        meta = self._registry.get(key)
        if not meta:
            return {
                "status": VerificationStatus.UNVERIFIED.value,
                "confidence": 0.0,
                "is_fresh": False,
                "data_reality": DataReality.SIMULATED.value,
                "badge": {"badge_type": "unverified", "badge_text": "[SIMULATED] No external feed available"}
            }
        
        is_fresh = meta.is_fresh()
        if meta.freshness_class != FreshnessClass.CLASS_U_UNKNOWN_UNVERIFIED:
            meta.verification_status = VerificationStatus.SOURCE_VERIFIED if is_fresh else VerificationStatus.STALE
            conf = meta.confidence if is_fresh else max(0.1, meta.confidence * 0.5)
        else:
            conf = 0.0
            
        return {
            "status": meta.verification_status.value,
            "confidence": conf,
            "is_fresh": is_fresh,
            "data_reality": meta.data_reality.value,
            "badge": meta.get_ui_badge()
        }
